name: ciudadano
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.17
  flutter_native_splash: ^2.4.5
  splash_master: ^0.0.2
  lottie: ^3.3.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  flutter_login: ^5.0.0
  dio: ^5.8.0+1
  logger: ^2.5.0
  local_auth: ^2.3.0
  sidebarx: ^0.17.1
  equatable: ^2.0.7
  skeletonizer: ^2.0.1
  flutter_map: 8.1.1
  geolocator: ^14.0.0
  latlong2: ^0.9.1
  dartz: ^0.10.1
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  flutter_hooks: ^0.20.3
  flutter_hooks_bloc: ^0.17.0
  socket_io_client: ^3.1.2
  permission_handler: ^12.0.0+1
  flutter_contacts_service: ^0.0.3
  flutter_chat_ui: ^2.6.1
  flutter_chat_core: ^2.6.2
  flutter_chat_types: ^3.6.2
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  syncfusion_flutter_datepicker: ^30.1.40
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.2
  flutter_map_location_marker: ^10.1.0
  flutter_map_compass: ^1.1.1
  # Firebase dependencies para notificaciones push
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^19.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/data/
    - assets/gifs/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
splash_master:
  color: "#000000"
  image: "assets/splash_screen.json"
flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo_foreground.png"
